### ISSUE TITLE
Removing product pom fails the build

### ISSUE THREAD

**Issue by vogella** [vogellacompany/tycho-example#12]
If I remove the product pom file the build fails. I though pomless build support that now. Any advice @laeubi?

**Comment by vogella** [comment]
Example branch for testing: https://github.com/vogellacompany/tycho-example/tree/pomlessproduct

**Comment by laeubi** [comment]
See https://github.com/vogellacompany/tycho-example/pull/13 for a complete example, you must upgrade the version in extension.xml to match new tycho-pomless 1.5.1

**Comment by vogella** [comment]
Works fine with latest Tycho, thanks @laeubi
