### ISSUE TITLE
Make the Java 11 requirement "official"?

### ISSUE THREAD

**Issue by mifritscher** [vogellacompany/tycho-example#16]
first: Thanks for this working example! One thing: The example does not work with Java 8, main log lines:

```
!ENTRY org.eclipse.equinox.simpleconfigurator 4 0 2021-11-22 09:44:17.944
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.simpleconfigurator [2]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))
```

So, would it be beneficial to raise the required execution environment in `com.vogella.tycho.rcp` to Java 11 as well?

**Comment by vogella** [comment]
Yes, please send pull request

mifritscher ***@***.***> schrieb am Mo., 22. Nov. 2021, 10:58:

**Comment by vogella** [comment]
Thanks.
