### ISSUE TITLE
Error with maven wrapped

### ISSUE THREAD

**Issue by flacher-nathan** [vogellacompany/tycho-example#30]
Hello,
I'm a french developer, my name is Nathan and I try to test your project to reproduce your configuration for a project,
but when I tried to run commands with your wrapped maven I got this error:

"'#' is not recognized as an internal order or external, an executable program or a command file."

On Powershell and on my WSL configuration with Ubuntu, do you know why?

Windows 10 (Powershell V5.1.19041.3693) :
![image](https://github.com/vogellacompany/tycho-example/assets/144113437/f3c3da99-d01f-4cfc-af5d-f00ee2b91276)
![image](https://github.com/vogellacompany/tycho-example/assets/144113437/5d194694-081c-4c97-bf44-efefcce7b818)

WSL2, Ubuntu :
![image](https://github.com/vogellacompany/tycho-example/assets/144113437/4e8ac696-8b96-40c3-b8ce-7f39834ec37c)
![image](https://github.com/vogellacompany/tycho-example/assets/144113437/846ed6a9-88b8-4885-8f44-3e53f78bcc5f)

**Comment by vogella** [comment]
Sorry, did not see this issue. Should be fixed with https://github.com/vogellacompany/tycho-example/pull/31
