### ISSUE TITLE
jenkins maven greater than 3.3.9 and code in subdirectory

### ISSUE THREAD

**Issue by benbrummer** [vogellacompany/tycho-example#7]
Hello, thanks for the nice example. We tried to build it on our Jenkins Server. We have found two problems when building the project.
It does not build when source is checked out to a subdirectory and -f subdirectory/pom.xml is used. Maven Versions greater than 3.3.9 fail.

### 3.3.9 and code in "sub"
`[Vogella] $ cmd.exe /C "c:\jenkins\tools\hudson.tasks.Maven_MavenInstallation\3.3.9\bin\mvn.cmd clean verify -V -B --file sub/pom.xml && exit %%ERRORLEVEL%%"
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: c:\jenkins\tools\hudson.tasks.Maven_MavenInstallation\3.3.9
Java version: 1.8.0_202, vendor: Oracle Corporation
Java home: c:\jenkins\tools\hudson.model.JDK\8\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module C:\jenkins\workspace\Vogella\sub\bundles\com.vogella.logging.config\pom.xml of C:\jenkins\workspace\Vogella\sub\bundles\pom.xml does not exist @ 
[ERROR] Child module C:\jenkins\workspace\Vogella\sub\bundles\com.vogella.tycho.plugin1\pom.xml of C:\jenkins\workspace\Vogella\sub\bundles\pom.xml does not exist @ 
[ERROR] Child module C:\jenkins\workspace\Vogella\sub\bundles\com.vogella.tycho.rcp\pom.xml of C:\jenkins\workspace\Vogella\sub\bundles\pom.xml does not exist @ 
[ERROR] Child module C:\jenkins\workspace\Vogella\sub\bundles\com.vogella.tycho.p2.ui\pom.xml of C:\jenkins\workspace\Vogella\sub\bundles\pom.xml does not exist @ 
[ERROR] Child module C:\jenkins\workspace\Vogella\sub\features\com.vogella.tycho.feature\pom.xml of C:\jenkins\workspace\Vogella\sub\features\pom.xml does not exist @ 
[ERROR] Child module C:\jenkins\workspace\Vogella\sub\tests\com.vogella.tycho.plugin1.tests\pom.xml of C:\jenkins\workspace\Vogella\sub\tests\pom.xml does not exist @ 
[ERROR] Child module C:\jenkins\workspace\Vogella\sub\tests\com.vogella.tycho.rcp.tests\pom.xml of C:\jenkins\workspace\Vogella\sub\tests\pom.xml does not exist @ 
 @ 
[ERROR] The build could not read 3 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.vogella.tycho:com.vogella.tycho.bundles:1.0.0-SNAPSHOT (C:\jenkins\workspace\Vogella\sub\bundles\pom.xml) has 4 errors
[ERROR]     Child module C:\jenkins\workspace\Vogella\sub\bundles\com.vogella.logging.config\pom.xml of C:\jenkins\workspace\Vogella\sub\bundles\pom.xml does not exist
[ERROR]     Child module C:\jenkins\workspace\Vogella\sub\bundles\com.vogella.tycho.plugin1\pom.xml of C:\jenkins\workspace\Vogella\sub\bundles\pom.xml does not exist
[ERROR]     Child module C:\jenkins\workspace\Vogella\sub\bundles\com.vogella.tycho.rcp\pom.xml of C:\jenkins\workspace\Vogella\sub\bundles\pom.xml does not exist
[ERROR]     Child module C:\jenkins\workspace\Vogella\sub\bundles\com.vogella.tycho.p2.ui\pom.xml of C:\jenkins\workspace\Vogella\sub\bundles\pom.xml does not exist
[ERROR]   
[ERROR]   The project com.vogella.tycho:com.vogella.tycho.features:1.0.0-SNAPSHOT (C:\jenkins\workspace\Vogella\sub\features\pom.xml) has 1 error
[ERROR]     Child module C:\jenkins\workspace\Vogella\sub\features\com.vogella.tycho.feature\pom.xml of C:\jenkins\workspace\Vogella\sub\features\pom.xml does not exist
[ERROR]   
[ERROR]   The project com.vogella.tycho:com.vogella.tycho.tests:1.0.0-SNAPSHOT (C:\jenkins\workspace\Vogella\sub\tests\pom.xml) has 2 errors
[ERROR]     Child module C:\jenkins\workspace\Vogella\sub\tests\com.vogella.tycho.plugin1.tests\pom.xml of C:\jenkins\workspace\Vogella\sub\tests\pom.xml does not exist
[ERROR]     Child module C:\jenkins\workspace\Vogella\sub\tests\com.vogella.tycho.rcp.tests\pom.xml of C:\jenkins\workspace\Vogella\sub\tests\pom.xml does not exist
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE`

### 3.6.0 and code root
`[Vogella] $ cmd.exe /C "c:\jenkins\tools\hudson.tasks.Maven_MavenInstallation\3.6.0\bin\mvn.cmd clean verify -V -B && exit %%ERRORLEVEL%%"
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: c:\jenkins\tools\hudson.tasks.Maven_MavenInstallation\3.6.0\bin\..
Java version: 1.8.0_202, vendor: Oracle Corporation, runtime: c:\jenkins\tools\hudson.model.JDK\8\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.vogella.tycho:com.vogella.tycho.root:1.0.0-SNAPSHOT: Could not find artifact com.vogella.tycho:com.vogella.tycho.configuration:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ com.vogella.tycho:com.vogella.tycho.root:1.0.0-SNAPSHOT, C:\jenkins\workspace\Vogella\pom.xml, line 7, column 10
[FATAL] Non-resolvable parent POM for com.vogella.tycho:com.vogella.tycho.root:1.0.0-SNAPSHOT: Could not find artifact com.vogella.tycho:com.vogella.tycho.configuration:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ com.vogella.tycho:com.vogella.tycho.root:1.0.0-SNAPSHOT, C:\jenkins\workspace\Vogella\pom.xml, line 7, column 10
[FATAL] Non-resolvable parent POM for com.vogella.tycho:com.vogella.tycho.root:1.0.0-SNAPSHOT: Could not find artifact com.vogella.tycho:com.vogella.tycho.configuration:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ com.vogella.tycho:com.vogella.tycho.root:1.0.0-SNAPSHOT, C:\jenkins\workspace\Vogella\pom.xml, line 7, column 10
[FATAL] Non-resolvable parent POM for com.vogella.tycho:com.vogella.tycho.root:1.0.0-SNAPSHOT: Could not find artifact com.vogella.tycho:com.vogella.tycho.configuration:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ com.vogella.tycho:com.vogella.tycho.root:1.0.0-SNAPSHOT, C:\jenkins\workspace\Vogella\pom.xml, line 7, column 10
 @ 
[ERROR] The build could not read 4 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.vogella.tycho:com.vogella.tycho.bundles:1.0.0-SNAPSHOT (C:\jenkins\workspace\Vogella\bundles\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.vogella.tycho:com.vogella.tycho.root:1.0.0-SNAPSHOT: Could not find artifact com.vogella.tycho:com.vogella.tycho.configuration:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ com.vogella.tycho:com.vogella.tycho.root:1.0.0-SNAPSHOT, C:\jenkins\workspace\Vogella\pom.xml, line 7, column 10 -> [Help 2]
[ERROR]   
[ERROR]   The project com.vogella.tycho:com.vogella.tycho.features:1.0.0-SNAPSHOT (C:\jenkins\workspace\Vogella\features\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.vogella.tycho:com.vogella.tycho.root:1.0.0-SNAPSHOT: Could not find artifact com.vogella.tycho:com.vogella.tycho.configuration:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ com.vogella.tycho:com.vogella.tycho.root:1.0.0-SNAPSHOT, C:\jenkins\workspace\Vogella\pom.xml, line 7, column 10 -> [Help 2]
[ERROR]   
[ERROR]   The project com.vogella.tycho:com.vogella.tycho.tests:1.0.0-SNAPSHOT (C:\jenkins\workspace\Vogella\tests\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.vogella.tycho:com.vogella.tycho.root:1.0.0-SNAPSHOT: Could not find artifact com.vogella.tycho:com.vogella.tycho.configuration:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ com.vogella.tycho:com.vogella.tycho.root:1.0.0-SNAPSHOT, C:\jenkins\workspace\Vogella\pom.xml, line 7, column 10 -> [Help 2]
[ERROR]   
[ERROR]   The project com.vogella.tycho:com.vogella.tycho.releng:1.0.0-SNAPSHOT (C:\jenkins\workspace\Vogella\releng\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.vogella.tycho:com.vogella.tycho.root:1.0.0-SNAPSHOT: Could not find artifact com.vogella.tycho:com.vogella.tycho.configuration:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ com.vogella.tycho:com.vogella.tycho.root:1.0.0-SNAPSHOT, C:\jenkins\workspace\Vogella\pom.xml, line 7, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
Build step 'Invoke top-level Maven targets' marked build as failure

Finished: FAILURE`

**Comment by benbrummer** [comment]
I opened a ticket https://issues.jenkins-ci.org/browse/JENKINS-56579. As the build works fine without jenkins involved

**Comment by vogella** [comment]
Thanks @benbrummer I also this issue
