### ISSUE TITLE
Build on console doesn't work

### ISSUE THREAD

**Issue by ingraban** [vogellacompany/tycho-example#9]
I cloned the repo and started the build at the command line with 
 `mvn clean verify`

This is the error log.
`
[INFO] 
[INFO] --- tycho-compiler-plugin:1.3.0:compile (default-compile) @ com.vogella.tycho.rcp ---
[INFO] Compiling 5 source files to /Users/saak/git/minova/vogella/bundles/com.vogella.tycho.rcp/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] com.vogella.tycho.root 1.0.0-SNAPSHOT .............. SUCCESS [  0.067 s]
[INFO] com.vogella.tycho.bundles .......................... SUCCESS [  0.006 s]
[INFO] com.vogella.logging.config ......................... SUCCESS [  2.127 s]
[INFO] com.vogella.tycho.plugin1 .......................... SUCCESS [  0.398 s]
[INFO] com.vogella.tycho.rcp .............................. FAILURE [  0.264 s]
[INFO] com.vogella.tycho.p2.ui ............................ SKIPPED
[INFO] com.vogella.tycho.features ......................... SKIPPED
[INFO] com.vogella.tycho.feature .......................... SKIPPED
[INFO] com.vogella.tycho.tests ............................ SKIPPED
[INFO] com.vogella.tycho.plugin1.tests .................... SKIPPED
[INFO] com.vogella.tycho.rcp.tests ........................ SKIPPED
[INFO] com.vogella.tycho.releng ........................... SKIPPED
[INFO] com.vogella.tycho.update ........................... SKIPPED
[INFO] com.vogella.tycho.product .......................... SKIPPED
[INFO] com.vogella.tycho.target 1.0.0-SNAPSHOT ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:06 min
[INFO] Finished at: 2019-04-17T13:16:00+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.3.0:compile (default-compile) on project com.vogella.tycho.rcp: Compilation failure: Compilation failure: 
[ERROR] /Users/saak/git/minova/vogella/bundles/com.vogella.tycho.rcp/src/com/vogella/tycho/rcp/handlers/QuitHandler.java:[1] 
[ERROR] 	package com.vogella.tycho.rcp.handlers;
[ERROR] 	^
[ERROR] The type org.eclipse.swt.widgets.Shell cannot be resolved. It is indirectly referenced from required .class files
[ERROR] /Users/saak/git/minova/vogella/bundles/com.vogella.tycho.rcp/src/com/vogella/tycho/rcp/handlers/QuitHandler.java:[6] 
[ERROR] 	import org.eclipse.swt.widgets.Shell;
[ERROR] 	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`

Why isn't it possible for Maven to resolve org.eclipse.swt.SWT. In eclipse the product runs without any problem.

**Comment by vogella** [comment]
Thanks Wilfried, I have a look.

Wilfried Saak <notifications@github.com> schrieb am Mi., 17. Apr. 2019,
13:30:

**Comment by vogella** [comment]
Thanks, fixed with the revert of the update site.

**Comment by vogella** [comment]
Updated to Tycho 1.4 and 2019-03 update site. The 32 bit references were still there and I had a reference to ds in the product file.
